
[DEFAULT]
******_password = ******
******_user = glance
******_tenant_name = service
auth_url = http://10.201.4.32/identity
image_cache_driver = centralized_db
image_cache_dir = /opt/stack/data/glance/cache/
use_syslog = False
debug = True

[glance_store]
filesystem_store_datadir = /opt/stack/data/glance/images/
