[keystone_authtoken]
memcached_servers = localhost:11211
cafile = /opt/stack/data/ca-bundle.pem
project_domain_name = Default
project_name = service
user_domain_name = Default
password = ******
username = cinder
auth_url = http://10.201.9.223/identity
interface = public
auth_type = password

[DEFAULT]
cinder_internal_tenant_user_id = 2bf2c9115c334adabbb8ede1f27a3bc3
cinder_internal_tenant_project_id = dca5e86c0d1b40b9be0724d07ce2929d
graceful_shutdown_timeout = 5
glance_api_servers = http://10.201.9.223/image
osapi_volume_workers = 2
logging_exception_prefix = ERROR %(name)s %(instance)s
logging_default_format_string = %(color)s%(levelname)s %(name)s [-%(color)s] %(instance)s%(color)s%(message)s
logging_context_format_string = %(color)s%(levelname)s %(name)s [%(global_request_id)s %(request_id)s %(project_name)s %(user_name)s%(color)s] %(instance)s%(color)s%(message)s
logging_debug_format_suffix = {{(pid=%(process)d) %(funcName)s %(pathname)s:%(lineno)d}}
transport_url = rabbit://stackrabbit:******@10.201.9.223:5672/
backup_swift_url = http://10.201.9.223:8080/v1/AUTH_
default_volume_type = 3par1
enabled_backends =3par1,3par2
my_ip = 10.201.9.223
state_path = /opt/stack/data/cinder
osapi_volume_listen = 0.0.0.0
osapi_volume_extension = cinder.api.contrib.standard_extensions
rootwrap_config = /etc/cinder/rootwrap.conf
api_paste_config = /etc/cinder/api-paste.ini
target_helper = tgtadm
debug = True

[database]
connection = mysql+pymysql://root:******@127.0.0.1/cinder?charset=utf8
sql_connection = mysql+pymysql://root:******@127.0.0.1/cinder?charset=utf8

[oslo_concurrency]
lock_path = /opt/stack/data/cinder

[key_manager]
fixed_key = bae3516cc1c0eb18b05440eba8012a4a880a2ee04d584a9c1579445e675b12defdc716ec
backend = cinder.keymgr.conf_key_mgr.ConfKeyManager

[lvmdriver-1]
image_volume_cache_enabled = True
volume_clear = zero
lvm_type = auto
target_helper = tgtadm
volume_group = stack-volumes-lvmdriver-1
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_backend_name = lvmdriver-1

[nova]
region_name = RegionOne
memcached_servers = localhost:11211
cafile = /opt/stack/data/ca-bundle.pem
project_domain_name = Default
project_name = service
user_domain_name = Default
password = ******
username = nova
auth_url = http://10.201.9.223/identity
interface = public
auth_type = password

#[coordination]
#backend_url = etcd3+http://10.201.9.223:2379

[backend_defaults]
unique_fqdn_network = False

[3par1]
volume_driver = cinder.volume.drivers.hpe.alletramp_driver.HPEAlletraMPISCSIDriver
hpe3par_api_url= https://10.201.5.12/api/v1
hpe_api_url_v3 = https://10.201.5.12/api/v3
hpe3par_iscsi_ips= 172.28.66.17
volume_backend_name= 3par1
hpe3par_username= 3paradm
hpe3par_password= ******
hpe3par_cpg= CI_CPG
# hpe3par_cpg = openstack_iscsi_one
san_ip= 10.201.5.12
san_login= 3paradm
san_password= ******
ssh_conn_timeout= 45
#use_multipath_for_image_xfer= True
hpe3par_hostseesvlun = True

[3par2]
volume_driver = cinder.volume.drivers.hpe.alletramp_driver.HPEAlletraMPISCSIDriver
hpe3par_api_url= https://10.201.5.12/api/v1
hpe_api_url_v3 = https://10.201.5.12/api/v3
hpe3par_iscsi_ips= 172.28.66.17
volume_backend_name= 3par2
hpe3par_username= 3paradm
hpe3par_password= ******
hpe3par_cpg= SSD_r6
# hpe3par_cpg = openstack_iscsi_two
san_ip= 10.201.5.12
san_login= 3paradm
san_password= ******
ssh_conn_timeout=45
#use_multipath_for_image_xfer = True
hpe3par_hostseesvlun = True


